osx_image: xcode10.2
language: objective-c

cache:
  directories:
    - Carthage
env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - PROJECT_NAME="PYPhotosViewExample/PYPhotosViewExample.xcodeproj"
    - SCHEME_IOS="PYPhotosViewExample"
    - IOS_SDK=iphonesimulator
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone XS" SCHEME="$SCHEME_IOS" SDK="$IOS_SDK"

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --no-use-binaries --cache-builds --platform iOS

script:
  - carthage build --no-skip-current --no-use-binaries --cache-builds --platform iOS
  - xcodebuild build -project "$PROJECT_NAME" -scheme "$SCHEME" -destination "$DESTINATION" -sdk "$SDK" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty -c

after_failure:
  - cat $TMPDIR/carthage-*.log